# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  #boot.kernelPackages = pkgs.linuxPackages_latest; 
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4f5909de-cf6f-47fb-be66-d57ad7d34001";
      fsType = "ext4";
    };

  fileSystems."/home/raysamram/MegaDrive" =
    { device = "/dev/disk/by-uuid/d63ff012-6992-479a-9796-6678b9586839";
      fsType = "ext4";
    };
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DA4C-DA80";
      fsType = "vfat";
    };

   

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f012f807-ed64-4362-a45c-ead9f7fed6c6"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp10s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
